export const ANIMAL_IMAGES = {
  "noobini pizzanini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114336.jpg",
  "lirili larila": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114346.jpg",
  "tim cheese": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114353.jpg",
  "fluriflura": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114400.jpg",
  "talpa di fero": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114410.jpg",
  "svinina bombardino": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114416.jpg",
  "pipi kiwi": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115543.jpg",
  "racooni jandelini": "https://static.beebom.com/wp-content/uploads/2025/07/Racooni-Jandelini.jpg",
  "pipi corni": "https://static.beebom.com/wp-content/uploads/2025/07/Pipi-Corni.jpg",
  "noobini santanini": "https://static.beebom.com/wp-content/uploads/2025/07/Noobini-Santanini.jpg",
  "trippi troppi": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-114424.jpg",
  "gangster footera": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115555.jpg",
  "bandito bobritto": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115602.jpg",
  "boneca ambalabu": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115610.jpg",
  "cacto hipopotamo": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115618.jpg",
  "ta ta ta ta sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115625.jpg",
  "tric trac baraboom": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-130413.jpg",
  "pipi avocado": "https://static.beebom.com/wp-content/uploads/2025/07/Steal-a-Brainrot-Pipi-Avocado.jpg",
  "frogo elfo": "https://static.beebom.com/wp-content/uploads/2025/07/Frogo-Elfo.jpg",
  "cappuccino assassino": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120740.jpg",
  "brr brr patapim": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115740.jpg",
  "trulimero trulicina": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115747.jpg",
  "bambini crostini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120747.jpg",
  "bananita dolphinita": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115755.jpg",
  "perochello lemonchello": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120755.jpg",
  "brri brri bicus dicus bombicus": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115802.jpg",
  "avocadini guffo": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120800.jpg",
  "salamino penguino": "https://static.beebom.com/wp-content/uploads/2025/07/Salamino-Penguino.jpg",
  "ti ti ti sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Ti-Ti-Ti-Sahur.jpg",
  "penguin tree": "https://static.beebom.com/wp-content/uploads/2025/07/Penguin-Tree.jpg",
  "penguino cocosino": "https://static.beebom.com/wp-content/uploads/2025/07/Penguino-Cocosino.jpg",
  "burbaloni loliloli": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115810.jpg",
  "chimpazini bananini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115814.jpg",
  "ballerina cappuccina": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115821.jpg",
  "chef crabracadabra": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115828.jpg",
  "lionel cactuseli": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120808.jpg",
  "glorbo fruttodrillo": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115836.jpg",
  "blueberrini octopusini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-125028.jpg",
  "strawberelli flamingelli": "https://static.beebom.com/wp-content/uploads/2025/07/image-32.jpg",
  "pandaccini bananini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-130442.jpg",
  "cocosini mama": "https://static.beebom.com/wp-content/uploads/2025/07/Cocosini-Mama.jpg",
  "sigma boy": "https://static.beebom.com/wp-content/uploads/2025/07/Sigma-Boy.jpg",
  "sigma girl": "https://static.beebom.com/wp-content/uploads/2025/07/Sigma-Girl.jpg",
  "pi pi watermelon": "https://static.beebom.com/wp-content/uploads/2025/07/Pi-Pi-Watermelon.jpg",
  "chocco bunny": "https://static.beebom.com/wp-content/uploads/2025/07/Chocco-Bunny.jpg",
  "sealo regalo": "https://static.beebom.com/wp-content/uploads/2025/07/Sealo-Regalo.jpg",
  "frigo camelo": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115843.jpg",
  "orangutini ananassini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115851.jpg",
  "rhino toasterino": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115858.jpg",
  "bombardiro crocodilo": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115912.jpg",
  "bombombini gusini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115921.jpg",
  "cavallo virtuso": "https://static.beebom.com/wp-content/uploads/2025/07/Cavallo-Virtuso.jpg",
  "gorillo watermelondrillo": "https://static.beebom.com/wp-content/uploads/2025/07/Gorillo-Watermelondrillo.jpg",
  "avocadorilla": "https://static.beebom.com/wp-content/uploads/2025/07/Avocadorilla.jpg",
  "tob tobi tobi": "https://static.beebom.com/wp-content/uploads/2025/07/Tob-Tobi-Tobi.jpg",
  "ganganzelli trulala": "https://static.beebom.com/wp-content/uploads/2025/07/Gangazelli-Trulala.jpg",
  "cachorrito melonito": "https://static.beebom.com/wp-content/uploads/2025/07/Cachorrito-Melonito.jpg",
  "elefanto frigo": "https://static.beebom.com/wp-content/uploads/2025/07/Elefanto-Frigo.jpg",
  "toiletto focaccino": "https://static.beebom.com/wp-content/uploads/2025/07/Toiletto-Focaccino.jpg",
  "te te te sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Te-Te-Te-Sahur.jpg",
  "tracoducotulu delapeladustuz": "https://static.beebom.com/wp-content/uploads/2025/07/Tracoducotulu-Delapeladustuz.jpg",
  "lerulerulerule": "https://static.beebom.com/wp-content/uploads/2025/07/Lerulerulerule.jpg",
  "jingle jingle sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Jingle-Jingle-Sahur.jpg",
  "tree tree tree sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Tree-Tree-Tree-Sahur.jpg",
  "carloo": "https://static.beebom.com/wp-content/uploads/2025/07/Carloo.jpg",
  "spioniro golubiro": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-130530.jpg",
  "zibra zubra zibralini": "https://static.beebom.com/wp-content/uploads/2025/07/image-30.jpg",
  "tigrilini watermelini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-130608.jpg",
  "carrotini brainini": "https://static.beebom.com/wp-content/uploads/2025/07/Carrotini-Brainini.jpg",
  "bananito bandito": "https://static.beebom.com/wp-content/uploads/2025/07/Bananito-Bandito.jpg",
  "coco elefanto": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115928.jpg",
  "girafa celestre": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120222.jpg",
  "gattatino nyanino": "https://static.beebom.com/wp-content/uploads/2025/07/Gyattatino-Nyanino.jpg",
  "chihuanini taconini": "https://static.beebom.com/wp-content/uploads/2025/07/Chihuanini-Taconini-1.jpg",
  "matteo": "https://static.beebom.com/wp-content/uploads/2025/07/Matteo.jpg",
  "tralalero tralala": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115943.jpg",
  "espresso signora": "https://static.beebom.com/wp-content/uploads/2025/07/image-29.jpg",
  "odin din din dun": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115945.jpg",
  "statutino libertino": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-131239.jpg",
  "trenostruzzo turbo 3000": "https://static.beebom.com/wp-content/uploads/2025/07/Trenostruzzo-Turbo-3000.jpg",
  "ballerino lololo": "https://static.beebom.com/wp-content/uploads/2025/07/image-33.png",
  "los orcalitos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Orcalitos.jpg",
  "dug dug dug": "https://static.beebom.com/wp-content/uploads/2025/07/Dug-Dug-Dug.jpg",
  "tralalita tralala": "https://static.beebom.com/wp-content/uploads/2025/07/Tralalita-Tralala.jpg",
  "urubini flamenguini": "https://static.beebom.com/wp-content/uploads/2025/07/Urubini-Flamenguini.jpg",
  "los bombinitos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Bombinitos-1.jpg",
  "trigoligre frutonni": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-131258.jpg",
  "orcalero orcala": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-131233.jpg",
  "bulbito bandito traktorito": "https://static.beebom.com/wp-content/uploads/2025/07/Bulbito-Bandito-Traktorito.jpg",
  "los crocodillitos": "https://static.beebom.com/wp-content/uploads/2025/07/Lost-Crocodilitos.jpg",
  "piccione macchina": "https://static.beebom.com/wp-content/uploads/2025/07/Piccione-Macchina.jpg",
  "trippi troppi troppa trippa": "https://static.beebom.com/wp-content/uploads/2025/07/Trippi-Troppi-Troppa-Trippa.jpg",
  "los tungtungtungcitos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Tungtuntuncitos.jpg",
  "tukanno bananno": "https://static.beebom.com/wp-content/uploads/2025/07/Tukanno-Bananno.jpg",
  "alessio": "https://static.beebom.com/wp-content/uploads/2025/07/Alessio.jpg",
  "tipi topi taco": "https://static.beebom.com/wp-content/uploads/2025/07/Tipi-Topi-Taco.jpg",
  "extinct ballerina": "https://static.beebom.com/wp-content/uploads/2025/07/Untitled-design-2.jpg",
  "capi taco": "https://static.beebom.com/wp-content/uploads/2025/07/Capi-Taco.jpg",
  "gattito tacoto": "https://static.beebom.com/wp-content/uploads/2025/07/Gattito-Tacoto-1.jpg",
  "pakrahmatmamat": "https://static.beebom.com/wp-content/uploads/2025/07/Pakrahmatmamat.jpg",
  "tractoro dinosauro": "https://static.beebom.com/wp-content/uploads/2025/07/Tractoro-Dinosauro-1.jpg",
  "corn corn corn sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Corn-Corn-Corn-Sahur.jpg",
  "squalanana": "https://static.beebom.com/wp-content/uploads/2025/07/Squalanana.jpg",
  "los tipi tacos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Tipi-Tacos-1.jpg",
  "bombardini tortinii": "https://static.beebom.com/wp-content/uploads/2025/07/Bombardini-Tortinii.jpg",
  "pop pop sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Pop-pop-sahur.jpg",
  "ballerina peppermintina": "https://static.beebom.com/wp-content/uploads/2025/07/Ballerina-Peppermintina.jpg",
  "yeti claus": "https://static.beebom.com/wp-content/uploads/2025/07/Yeti-Claus-1.jpg",
  "ginger globo": "https://static.beebom.com/wp-content/uploads/2025/07/Ginger-Globo.jpg",
  "frio ninja": "https://static.beebom.com/wp-content/uploads/2025/07/Frio-Ninja.jpg",
  "ginger cisterna": "https://static.beebom.com/wp-content/uploads/2025/07/Ginger-Cisterna.jpg",
  "cacasito satalito": "https://static.beebom.com/wp-content/uploads/2025/11/Cacasito-Satalito-1.jpg",
  "aquanaut": "https://static.beebom.com/wp-content/uploads/2025/11/Aquanaut.jpg",
  "tartaruga cisterna": "https://static.beebom.com/wp-content/uploads/2025/11/Tartaruga-Cisterna-1.jpg",
  "las sis": "https://static.beebom.com/wp-content/uploads/2025/07/Las-Sis.jpg",
  "la vacca staturno saturnita": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-115952.jpg",
  "chimpanzini spiderini": "https://static.beebom.com/wp-content/uploads/2025/07/Chimpanzini_spiderini.webp",
  "extinct tralalero": "https://static.beebom.com/wp-content/uploads/2025/07/Extinct-Tralalero.jpg",
  "extinct matteo": "https://static.beebom.com/wp-content/uploads/2025/07/Extinct-Matteo.jpg",
  "los tralaleritos": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120001.jpg",
  "la karkerkar combinasion": "https://static.beebom.com/wp-content/uploads/2025/07/La-Karkerkar-Combinasion.jpg",
  "karker sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Karker-Sahur.jpg",
  "las tralaleritas": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-131442.jpg",
  "job job job sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Job-Job-Job-Sahur.jpg",
  "los spyderrinis": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Spyderinis.jpg",
  "perrito burrito": "https://static.beebom.com/wp-content/uploads/2025/07/Perrito-Burrito.jpg",
  "graipuss medussi": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120008.jpg",
  "los jobcitos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Jobcitos.jpg",
  "la grande combinasion": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-120331.jpg",
  "tacorita bicicleta": "https://static.beebom.com/wp-content/uploads/2025/07/Tacorita-Bicicleta.jpg",
  "nuclearo dinossauro": "https://static.beebom.com/wp-content/uploads/2025/07/image-34.jpg",
  "los 67": "https://static.beebom.com/wp-content/uploads/2025/07/Los-67.jpg",
  "money money puggy": "https://static.beebom.com/wp-content/uploads/2025/07/Money-Money-Puggy.jpg",
  "chillin chili": "https://static.beebom.com/wp-content/uploads/2025/07/Chillin-chili.jpg",
  "la extinct grande": "https://static.beebom.com/wp-content/uploads/2025/07/La-Extinct-Grande.jpg",
  "los tacoritas": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Tacoritas.jpg",
  "los tortus": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Tortus.jpg",
  "tang tang kelentang": "https://static.beebom.com/wp-content/uploads/2025/07/Tang-Tang-Keletang.jpg",
  "garama and madundung": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-133543-Photoroom.jpg",
  "la secret combinasion": "https://static.beebom.com/wp-content/uploads/2025/07/La-Secret-combinasion.jpg",
  "torrtuginni dragonfruitini": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-131117.jpg",
  "pot hotspot": "https://static.beebom.com/wp-content/uploads/2025/07/Screenshot-2025-07-25-131122.jpg",
  "to to to sahur": "https://static.beebom.com/wp-content/uploads/2025/07/To-to-to-Sahur.jpg",
  "las vaquitas saturnitas": "https://static.beebom.com/wp-content/uploads/2025/07/Las-Vaquitas-Saturnitas.jpg",
  "chicleteira bicicleteira": "https://static.beebom.com/wp-content/uploads/2025/07/Chicleteira-Bicicleteira.jpg",
  "agarrini la palini": "https://static.beebom.com/wp-content/uploads/2025/07/Agarrini-la-Palini.jpg",
  "mariachi corazoni": "https://static.beebom.com/wp-content/uploads/2025/07/Mariachi-corazoni.jpg",
  "dragon cannelloni": "https://static.beebom.com/wp-content/uploads/2025/07/Dragon-Cannelloni.jpg",
  "los combinasionas": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Combinasionas.jpg",
  "la cucaracha": "https://static.beebom.com/wp-content/uploads/2025/07/La-Cucaracha.jpg",
  "karkerkar kurkur": "https://static.beebom.com/wp-content/uploads/2025/07/Karkerkar-Kurkur.jpg",
  "los hotspotsitos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Hotspotsitos.jpg",
  "la sahur combinasion": "https://static.beebom.com/wp-content/uploads/2025/07/La-Sahur-Combinasion.jpg",
  "quesadilla crocodila": "https://static.beebom.com/wp-content/uploads/2025/07/Quesadilla-Crocodila.jpg",
  "esok sekolah": "https://static.beebom.com/wp-content/uploads/2025/07/Esok-Sekolah.jpg",
  "los matteos": "https://static.beebom.com/wp-content/uploads/2025/07/Lost-Matteos.jpg",
  "dul dul dul": "https://static.beebom.com/wp-content/uploads/2025/07/Dul-Dul-Dul.jpg",
  "blackhole goat": "https://static.beebom.com/wp-content/uploads/2025/07/Blackhole-Goat.jpg",
  "nooo my hotspot": "https://static.beebom.com/wp-content/uploads/2025/07/Nooo-My-Hotspot.jpg",
  "sammyini spyderini": "https://static.beebom.com/wp-content/uploads/2025/07/Sammyini-Spyderini.jpg",
  "spaghetti tualetti": "https://static.beebom.com/wp-content/uploads/2025/07/Spaghetti-Tualetti.jpg",
  "67": "https://static.beebom.com/wp-content/uploads/2025/07/67-Brainrot.jpg",
  "los noo my hotspotsitos": "https://static.beebom.com/wp-content/uploads/2025/07/Los-Noo-My-Hotspotsitos.jpg",
  "celularcini viciosini": "https://static.beebom.com/wp-content/uploads/2025/07/Celularcini-Viciosini.jpg",
  "tralaledon": "https://static.beebom.com/wp-content/uploads/2025/07/Tralaledon.jpg",
  "tictac sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Tictac-sahur.jpg",
  "la supreme combinasion": "https://static.beebom.com/wp-content/uploads/2025/07/La-Supreme-Combinasion.jpg",
  "ketupat kepat": "https://static.beebom.com/wp-content/uploads/2025/07/Ketupat-Kepat.jpg",
  "ketchuru and musturu": "https://static.beebom.com/wp-content/uploads/2025/07/Ketchuru-and-Musturu-1.jpg",
  "burguro and fryuro": "https://static.beebom.com/wp-content/uploads/2025/07/Burguro-and-Fryuro.jpg",
  "please my present": "https://static.beebom.com/wp-content/uploads/2025/07/Please-my-Present.jpg",
  "la grande": "https://static.beebom.com/wp-content/uploads/2025/07/La-Grande.jpg",
  "la vacca prese presente": "https://static.beebom.com/wp-content/uploads/2025/07/La-Vacca-Prese-Presente.jpg",
  "ho ho ho sahur": "https://static.beebom.com/wp-content/uploads/2025/07/Ho-Ho-Ho-Sahur.jpg",
  "chicleteira noelteira": "https://static.beebom.com/wp-content/uploads/2025/07/Chicleteira-Noelteira.jpg",
  "cooki and milki": "https://static.beebom.com/wp-content/uploads/2025/07/Cooki-and-Milki.jpg",
  "la jolly grande": "https://static.beebom.com/wp-content/uploads/2025/07/La-Jolly-Grande.jpg",
  "capitano moby": "https://static.beebom.com/wp-content/uploads/2025/11/Capitano-Moby.jpg",
  "cerberus": "https://static.beebom.com/wp-content/uploads/2025/11/Cerberus.jpg",
  "skibidi toilet": "https://static.beebom.com/wp-content/uploads/2025/07/Skibidi-Toilet-1.jpg",
  "strawberry elephant": "https://static.beebom.com/wp-content/uploads/2025/07/Strawberry-Elephant-1.jpg",
  "meowl": "https://static.beebom.com/wp-content/uploads/2025/07/Meowl.jpg",
}

export function getAnimalImage(name) {
  return ANIMAL_IMAGES[name.toLowerCase().trim()] || null
}
